# Generated by Django 3.1.6 on 2021-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1250)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.CharField(max_length=250)),
            ],
        ),
    ]
