# Generated by Django 3.1.6 on 2021-02-16 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='wY6UyatwVTA', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
